"""
AST-based extraction of asset tags from user code.

Walks the AST to find string literals matching asset patterns,
validates that they appear in valid usage contexts (assignments, calls,
returns, container literals), and generates preamble code + source
replacements so the user's code can reference assets by their raw IDs inline.
"""

import ast
from typing import Sequence, Set

from .types import ASSET_TAG_RE, ASSET_TAG_UNCLOSED_RE

# AST node types that represent a valid "usage" context for a string literal
# containing a handle ID or asset tag.  A bare expression statement (e.g. a
# docstring or standalone ``"h_abc123def456"``) is intentionally excluded.
_VALID_PARENT_TYPES = (
    ast.Assign,
    ast.AnnAssign,
    ast.Call,
    ast.keyword,
    ast.Return,
    ast.Dict,
    ast.List,
    ast.Tuple,
    ast.Set,
)

# Reserved prefix for synthetic variable names generated by auto-extraction.
# Uses a double-underscore + namespace prefix to avoid collisions with user code.
_VAR_PREFIX_ASSET = "__agora_asset_"


def collect_code_names(code: str) -> Set[str]:
    """Return all identifier names used in *code* (loads, stores, and deletes).

    This performs an AST parse and collects every ``ast.Name`` node,
    giving a complete picture of which variable names appear in the
    source.  Returns an empty set if the code has a syntax error.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return set()
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def generate_safe_varname(
    prefix: str,
    counter: int,
    occupied: Set[str],
) -> tuple[str, int]:
    """Generate a synthetic variable name that does not collide with *occupied*.

    Starts with ``f"{prefix}{counter}"`` and increments *counter* until
    the candidate is not in *occupied*.  Returns the safe name **and**
    the next counter value (so callers can pass it into subsequent calls).

    >>> generate_safe_varname("__agora_handle_", 0, {"__agora_handle_0"})
    ('__agora_handle_1', 2)
    """
    candidate = f"{prefix}{counter}"
    while candidate in occupied:
        counter += 1
        candidate = f"{prefix}{counter}"
    # Reserve the name we just chose so later calls see it as occupied.
    occupied.add(candidate)
    return candidate, counter + 1


def _add_parents(tree: ast.AST) -> None:
    """Annotate every AST node with a ``_parent`` attribute."""
    for node in ast.walk(tree):
        for child in ast.iter_child_nodes(node):
            child._parent = node  # type: ignore[attr-defined]


def _in_valid_context(node: ast.AST) -> bool:
    """Return True when *node* sits inside a usage context (not a bare expr / docstring)."""
    current = node
    while hasattr(current, "_parent"):
        parent = current._parent  # type: ignore[attr-defined]
        if isinstance(parent, _VALID_PARENT_TYPES):
            # For ast.Assign, the literal must be on the *value* side.
            if isinstance(parent, ast.Assign) and current in parent.targets:
                return False
            return True
        # Keep walking up — e.g. a Tuple inside an Assign is fine.
        current = parent
    return False


RefKind = str  # Always "asset" now


def extract_references(
    code: str,
) -> tuple[
    list[tuple[ast.Constant, RefKind, str]],
    dict[str, list[tuple[ast.Constant, str]]],
    Set[str],
]:
    """Find string literals that are asset tags in valid contexts.

    Returns a 3-tuple of:
      - A deduplicated list of ``(ast_node, kind, value)`` — one per unique value.
      - A dict mapping each matched *value* to **all** its occurrences as
        ``(ast_node, value)`` pairs in valid contexts (for replacement).
      - A set of all identifier names (``ast.Name`` nodes) found in the code,
        useful for collision-free synthetic variable generation.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return [], {}, set()

    _add_parents(tree)

    seen_values: set[str] = set()
    unique_refs: list[tuple[ast.Constant, RefKind, str]] = []
    all_occurrences: dict[str, list[tuple[ast.Constant, str]]] = {}
    code_names: Set[str] = set()

    for node in ast.walk(tree):
        # Collect all identifier names for collision avoidance
        if isinstance(node, ast.Name):
            code_names.add(node.id)
            continue

        if not isinstance(node, ast.Constant) or not isinstance(node.value, str):
            continue

        value = node.value

        kind: RefKind | None = None
        if ASSET_TAG_RE.match(value):
            kind = "asset"
        elif ASSET_TAG_UNCLOSED_RE.match(value):
            # LLM sometimes omits the closing tag — accept unclosed tags too
            kind = "asset"

        if kind is None:
            continue

        if not _in_valid_context(node):
            continue

        # Track all occurrences for replacement
        all_occurrences.setdefault(value, []).append((node, value))

        # Deduplicated list for validation/preamble generation
        if value not in seen_values:
            seen_values.add(value)
            unique_refs.append((node, kind, value))

    return unique_refs, all_occurrences, code_names


def replace_literals_in_source(
    source_lines: Sequence[str],
    replacements: list[tuple[ast.Constant, str]],
) -> list[str]:
    """Replace string-literal spans in *source_lines* with variable names.

    *replacements* is a list of ``(ast_node, var_name)`` pairs.  Processing
    is done in reverse position order so that earlier replacements don't
    shift the offsets of later ones.
    """
    # Sort in reverse order (last line first, then last column first)
    sorted_replacements = sorted(
        replacements,
        key=lambda r: (r[0].lineno, r[0].col_offset),
        reverse=True,
    )

    lines = list(source_lines)  # shallow copy

    for node, var_name in sorted_replacements:
        start_line = node.lineno - 1  # 0-indexed
        start_col = node.col_offset
        end_line = node.end_lineno - 1  # type: ignore[operator]
        end_col = node.end_col_offset  # type: ignore[assignment]

        if start_line == end_line:
            line = lines[start_line]
            lines[start_line] = line[:start_col] + var_name + line[end_col:]
        else:
            # Multi-line string literal — replace the full span
            first_line = lines[start_line]
            last_line = lines[end_line]
            lines[start_line] = first_line[:start_col] + var_name + last_line[end_col:]
            del lines[start_line + 1 : end_line + 1]

    return lines


def build_asset_preamble(var_name: str, cache_path: str) -> list[str]:
    """Return preamble lines that create a Path variable pointing to a cached asset.

    Uses a namespaced import (``import pathlib as __agora_pathlib``) to
    avoid overwriting a user-defined ``Path`` name.  The caller should
    ensure the import line is emitted only once in the preamble.
    """
    return [
        f"{var_name} = __agora_pathlib.Path({cache_path!r})",
    ]


# The single import line emitted at the top of the asset preamble.
ASSET_PATHLIB_IMPORT = "import pathlib as __agora_pathlib"
