"""Backend-neutral public contracts for data-lake access."""

from .errors import (
    ArtifactNotFoundError,
    BackendUnavailableError,
    DataLakeError,
    DataLakeErrorCode,
    InvalidRequestError,
    PermissionDeniedError,
    UnsupportedOperationError,
)
from .identity import (
    azure_uri_from_blob_name,
    canonicalize_azure_uri,
    logical_artifact_id,
    normalize_logical_path,
    parse_azure_uri,
    sanitize_uri_for_display,
    split_alias,
    stable_source_id,
)
from .models import (
    MAX_PAGE_LIMIT,
    READ_OPERATIONS,
    ArtifactPresentation,
    ArtifactReference,
    CatalogAuthorizationRequest,
    CatalogArtifact,
    CatalogOperation,
    CatalogPolicyMode,
    DownloadInfo,
    ListRequest,
    Page,
    PageRequest,
    RequestContext,
    ResolvedArtifact,
    ResourceLease,
    ResourceOwnership,
    SearchRequest,
    SourceCapabilities,
    StorageLocator,
)
from .manifest import (
    MANIFEST_VERSION,
    MAX_MANIFEST_ARTIFACTS,
    MAX_MANIFEST_BYTES,
    CatalogManifest,
    ManifestArtifact,
)
from .policy import AuthorizedCatalogProvider, DenyAllCatalogAuthorizer, DevelopmentAllowAllCatalogAuthorizer
from .protocols import (
    ArtifactResolver,
    CatalogAuthorizer,
    CatalogPolicyEnforcer,
    CatalogProvider,
    PolicyEnforcedCatalog,
)

__all__ = [
    "ArtifactNotFoundError",
    "ArtifactPresentation",
    "ArtifactReference",
    "ArtifactResolver",
    "AuthorizedCatalogProvider",
    "BackendUnavailableError",
    "CatalogArtifact",
    "CatalogManifest",
    "CatalogAuthorizationRequest",
    "CatalogAuthorizer",
    "CatalogOperation",
    "CatalogPolicyEnforcer",
    "CatalogPolicyMode",
    "CatalogProvider",
    "DataLakeError",
    "DataLakeErrorCode",
    "DownloadInfo",
    "DenyAllCatalogAuthorizer",
    "DevelopmentAllowAllCatalogAuthorizer",
    "InvalidRequestError",
    "ListRequest",
    "MAX_PAGE_LIMIT",
    "MAX_MANIFEST_ARTIFACTS",
    "MAX_MANIFEST_BYTES",
    "MANIFEST_VERSION",
    "ManifestArtifact",
    "Page",
    "PageRequest",
    "PolicyEnforcedCatalog",
    "PermissionDeniedError",
    "READ_OPERATIONS",
    "RequestContext",
    "ResolvedArtifact",
    "ResourceLease",
    "ResourceOwnership",
    "SearchRequest",
    "SourceCapabilities",
    "StorageLocator",
    "UnsupportedOperationError",
    "azure_uri_from_blob_name",
    "canonicalize_azure_uri",
    "logical_artifact_id",
    "normalize_logical_path",
    "parse_azure_uri",
    "sanitize_uri_for_display",
    "split_alias",
    "stable_source_id",
]
