"""Shared constants for the Azure AI Search tool index."""

TOOL_SEARCH_ENDPOINT_ENV = "TOOL_SEARCH_ENDPOINT"
TOOL_SEARCH_VECTORIZER_ENDPOINT_ENV = "TOOL_SEARCH_VECTORIZER_ENDPOINT"
TOOL_SEARCH_VECTORIZER_DEPLOYMENT_ENV = "TOOL_SEARCH_VECTORIZER_DEPLOYMENT"
_OPENAI_EMBEDDING_API_VERSION = "2024-06-01"
